language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: e0y5Ff44AFxLMUpG0hcsoTIw7QIc9NKCBPFRXPKGM72NCG1qsoi4r4ETxSGLEHwpWQUxhuCbUcdIvwZJKd3ZOq77vcxWE9FxYSMctMrMYanLgdTlFhRJ02E52xvxhAm8JB64y5Qi1RZtlhGrWUm9DFD+uCmDrvWURZquXPYqP00+tUN3jWUpy52Di1uOz51bSmYJacw2vL6u/iyfYwFd4MD3jhmSJHUY7OdkXZCUH9zsWrCJS5HftWcN7L5RaSRCzebd5s+ckvERZFtwDNrREObTCoj8uCKUcmeC/OsF0IDw40xpkCRYI+F2CPktY/7GsHFvvZ9ETaS+RKARCWI0L8YH5WybhIFzwxM6+REs88itqj70484L7F/0HMveu2m8kzczCeraJZRheJcZeCz+HBuvekZexGiS4nPQGMnTQvba5Bu1Q8YOMEODcuVxZh+pzJxxghHam9lRKf09XuUct38OmZdFOXVFg60nHBOKfZzAkBKoY+f4d+Z2b8p+BeapX9Ol4WTIzEXj0+wIfzfJ99BhrRvKbsqsCRYpO6XyVUcN+HNIOPezFGFgpsxLU9LaQG7w/0EqosV4QxeW0t5/En+4Ti2wFy4Xk8hyhvrFAMc1gRGZgIZv4nU2Hb890NHJyyMjFOzhGmmFG2RHk0Xpoo5KxfEzuSuwXcYK7Yq0qPQ=
  app: glacial-savannah-27342
  on:
    repo: tcw5038/blog-app-mongoose-challenge-solution
